### ISSUE TITLE
项目如何编译?

### ISSUE THREAD

**Issue by leviathan0992** [netcan/compilingTheory#1]
这个项目如何编译，README里面没有提及编译.

**Comment by netcan** [comment]
每个实验文件夹下有个makefile文件，在Linux上面，运行make，就会编译成二进制了。
或者自己调用编译器编译，
```
clang++ LR.cpp -o LR
```

**Comment by leviathan0992** [comment]
@netcan 整个系统可以在LAMP环境下运行吗?

**Comment by leviathan0992** [comment]
我的系统是Centos, 然后我把项目放在`/var/www/html`下, 然后访问服务器的时候发现页面显示不完整,只有html显示.

**Comment by leviathan0992** [comment]
谢谢解决了.
