### ISSUE TITLE
看了一下词法分析器，发现实现的方法是遍历而不是转DFA？

### ISSUE THREAD

**Issue by ihewro** [netcan/compilingTheory#2]
你好，看了你实现了词法分析器，似乎是**直接for循环遍历输入的每个字符**，

比如“匹配数字字符串自动机”，具体实现代码是：

```c++
else if(isdigit(c)) {
            for(j = column+1; j < in.length() && (isalnum(in[j]) || in[j] == '_'); ++j); // 匹配数字字符串自动机
            string s = cut(column, j);

            if(!isFirst) printf(", ");
            else isFirst = false;
            if(isNum(s))
                printf("{\"word\": \"%s\", \"tuple\": [%d, %d], \"type\": \"%s\", \"pos\": [%d, %d]}\n", s.c_str(), NUMBER, getNumPointer(s), typeStr[NUMBER], row, column+1);
            else
                printf("{\"word\": \"%s\", \"tuple\": [%d, %d], \"type\": \"%s\", \"pos\": [%d, %d]}\n", s.c_str(), ERROR, ERROR, typeStr[ERROR], row, column+1);

            column = j - 1;
        }
```

而不是课本上面的

1. 先写正则表达式：`0|1|2|3|4|5|6|7|8|9` 
2. 然后转NFA再转DFA,再最小化，最后判断输入的内容能否走到最终的状态来判断是否是数字

还是说这两种思路是一种思路呢？
或者是两种方法都可以实现的，但是效率有区别，或者是效率没区别呢？

初学编译原理，请教指点

**Comment by netcan** [comment]
是需要转NFA->DFA在最小化，实现起来可以用for循环。比如匹配数字，for里面的(isalnum(in[j]) || in[j] == '_')这个条件满足就是不断转移到0这个状态，不满足的话跳出for，也就跳出0状态了，匹配结束。

![image](https://user-images.githubusercontent.com/11377070/34080499-04ce30c4-e37a-11e7-906f-2161a51b9e2f.png)
