### ISSUE TITLE
请问下网页运行的时候为什么报这个错

### ISSUE THREAD

**Issue by yuirito** [netcan/compilingTheory#6]
![G96FF27MKMRX55T2 5RHLK5](https://user-images.githubusercontent.com/40927814/86129133-cc53b780-bb14-11ea-978b-adf6d9268095.png)

![QQ截图20200630125220](https://user-images.githubusercontent.com/40927814/86129080-c067f580-bb14-11ea-83d1-46223edbaeb0.jpg)

**Comment by netcan** [comment]
用make编译后，需要nginx/php服务器，这个有么？

**Comment by yuirito** [comment]
明白了，谢谢
